type Funcionario {
    idFuncionario: ID!
    status: String!
    nome: String!
    tipo: String!
    email: String!
    idSession: String
}

type Query {
    funcionarios: [Funcionario]!
    funcionario(idFuncionario: ID!): Funcionario!
    funcionariosByNome(nome: String!): [Funcionario]!
    funcionariosByStatus(status: String!): [Funcionario]!
    searchFuncionarios(filter: FuncionarioFilter): [Funcionario]!
    confereLogin(email: String!): Funcionario
    confereSession(idSession: String!): Funcionario
}

input FuncionarioFilter {
    status: String
    nome: String
}

input DadosFuncionario{
    status: String
    nome: String
    tipo: String
    email: String
    idSession: String
}

type Mutation {
    createFuncionario(data: DadosFuncionario!): Funcionario!
    updateFuncionario(idFuncionario: ID!, data: DadosFuncionario!): Funcionario!
    updateIdSession(idFuncionario: ID!, idSession: String!): Funcionario!
    deleteFuncionario(idFuncionario: ID!): Boolean!
}